/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lib.Author;
import lib.Book;
import lib.Magazine;

/**
 *
 * @author BISHNU
 */
public class AddPublication extends javax.swing.JPanel {

    /**
     * Creates new form AddPublication
     */
    public AddPublication() {
        initComponents();

        showAllControls(true);
        jLabel3.setVisible(false);
        issueNoTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        issueNoTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        isbnTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lastNameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        credentialsTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        shortBioTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        streetTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stateTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        zipTF = new javax.swing.JTextField();
        addAuthorAddressBtn = new javax.swing.JButton();
        addPublicationBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        authorAddressTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookListTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        magazineListTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel1.setText("Title");

        jLabel2.setText("Choose Type");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book", "Magazine" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("IssueNo");

        jLabel4.setText("ISBN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Author");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Books");

        jLabel7.setText("Last Name");

        jLabel8.setText("Phone");

        phoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTFActionPerformed(evt);
            }
        });

        jLabel9.setText("Credentials");

        credentialsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credentialsTFActionPerformed(evt);
            }
        });

        jLabel10.setText("Short Bio");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Address");

        jLabel12.setText("Street");

        jLabel13.setText("City");

        jLabel14.setText("State");

        jLabel15.setText("Zip");

        addAuthorAddressBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addAuthorAddressBtn.setForeground(new java.awt.Color(0, 0, 153));
        addAuthorAddressBtn.setText("Add Author and his/her Address");
        addAuthorAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorAddressBtnActionPerformed(evt);
            }
        });

        addPublicationBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addPublicationBtn.setForeground(new java.awt.Color(0, 0, 153));
        addPublicationBtn.setText("Add Publication");
        addPublicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPublicationBtnActionPerformed(evt);
            }
        });

        authorAddressTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        authorAddressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Phone", "Credentials", "Short Bio", "Street", "City", "State", "Zip"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(authorAddressTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        bookListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "ISBN", "Authors"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bookListTable);

        magazineListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(magazineListTable);

        jLabel16.setText("First Name");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Magazines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeComboBox, 0, 1, Short.MAX_VALUE)
                            .addComponent(titleTF)
                            .addComponent(issueNoTF)
                            .addComponent(firstNameTF)
                            .addComponent(lastNameTF)
                            .addComponent(phoneTF)
                            .addComponent(isbnTF)
                            .addComponent(credentialsTF)
                            .addComponent(shortBioTF)
                            .addComponent(streetTF)
                            .addComponent(cityTF)
                            .addComponent(stateTF)
                            .addComponent(zipTF)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addPublicationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(addAuthorAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isbnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(credentialsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(shortBioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(streetTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(stateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(zipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(addAuthorAddressBtn)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel17))
                            .addComponent(addPublicationBtn)))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTFActionPerformed

    private void credentialsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credentialsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credentialsTFActionPerformed

    private void addAuthorAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorAddressBtnActionPerformed
        // TODO add your handling code here:

        String firstName = firstNameTF.getText();
        String lastName = lastNameTF.getText();
        String phone = phoneTF.getText();
        String credentials = credentialsTF.getText();
        String shortBio = shortBioTF.getText();
        String street = streetTF.getText();
        String city = cityTF.getText();
        String state = stateTF.getText();
        String zip = zipTF.getText();

        if (firstName.length() == 0 || lastName.length() == 0
                || phone.length() == 0 || credentials.length() == 0 || shortBio.length() == 0
                || street.length() == 0 || city.length() == 0 || state.length() == 0
                || zip.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Fillup all fields of Author and Address");

        } else {
            DefaultTableModel model = (DefaultTableModel) authorAddressTable.getModel();
            model.addRow(new Object[]{firstName, lastName, phone, credentials, shortBio, street, city, state, zip});

            clearAuthorAddress();
            firstNameTF.requestFocus();

        }

    }//GEN-LAST:event_addAuthorAddressBtnActionPerformed

    private void clearAuthorAddress() {
        firstNameTF.setText("");
        lastNameTF.setText("");
        phoneTF.setText("");
        credentialsTF.setText("");
        shortBioTF.setText("");
        streetTF.setText("");
        cityTF.setText("");
        stateTF.setText("");
        zipTF.setText("");
    }

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:

        String selectedItem = typeComboBox.getSelectedItem().toString();
        if (selectedItem.equalsIgnoreCase("Magazine")) {
            showAllControls(false);
            jLabel3.setVisible(true);
            issueNoTF.setVisible(true);
        } else if (selectedItem.equalsIgnoreCase("Book")) {
            showAllControls(true);
            jLabel3.setVisible(false);
            issueNoTF.setVisible(false);
        }


    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void addPublicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPublicationBtnActionPerformed
        // TODO add your handling code here:

        String typeOfPublication = typeComboBox.getSelectedItem().toString();
        String title = titleTF.getText();

        if (typeOfPublication.equalsIgnoreCase("Book")) {
            String isbn = isbnTF.getText();
//            String firstName = firstNameTF.getText();
//            String lastName = lastNameTF.getText();
//            String phone = phoneTF.getText();
//            String credentials = credentialsTF.getText();
//            String shortBio = shortBioTF.getText();
//            String street = streetTF.getText();
//            String city = cityTF.getText();
//            String state = stateTF.getText();
//            String zip = zipTF.getText();

            List<Author> authorList = new ArrayList<Author>();

            DefaultTableModel model = (DefaultTableModel) authorAddressTable.getModel();

            if (model.getRowCount() > 0) {
                for (int i = model.getRowCount() - 1; i > -1; i--) {
                    String firstName = authorAddressTable.getValueAt(i, 0).toString();
                    String lastName = authorAddressTable.getValueAt(i, 1).toString();
                    String phone = authorAddressTable.getValueAt(i, 2).toString();
                    String credentials = authorAddressTable.getValueAt(i, 3).toString();
                    String shortBio = authorAddressTable.getValueAt(i, 4).toString();
                    String street = authorAddressTable.getValueAt(i, 5).toString();
                    String city = authorAddressTable.getValueAt(i, 6).toString();
                    String state = authorAddressTable.getValueAt(i, 7).toString();
                    String zip = authorAddressTable.getValueAt(i, 8).toString();

                    Author author = new Author(firstName, lastName, phone, credentials,shortBio, street, city, state, zip);

                    authorList.add(author);

                }
            }

            Collections.reverse(authorList);

            Book book = new Book(title, isbn, authorList);
            LibrarySystemApplication.getInstance().getPubBookList().add(book);
            DefaultTableModel modelBook = (DefaultTableModel) bookListTable.getModel();
            modelBook.addRow(new Object[]{title, isbn, showAuthors(authorList)});
            JOptionPane.showMessageDialog(null, "Successfully Book Publication Added");

        } else if (typeOfPublication.equalsIgnoreCase("Magazine")) {

            String issueNo = issueNoTF.getText();
            Magazine magazine = new Magazine(title, issueNo);
            LibrarySystemApplication.getInstance().getPubMagazineList().add(magazine);
            DefaultTableModel modelMag = (DefaultTableModel) magazineListTable.getModel();
            modelMag.addRow(new Object[]{title});
            JOptionPane.showMessageDialog(null, "Successfully Magazine Publication Added");

        }

        DefaultTableModel model = (DefaultTableModel) authorAddressTable.getModel();

        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        titleTF.setText("");
        issueNoTF.setText("");
        isbnTF.setText("");

        titleTF.requestFocus();


    }//GEN-LAST:event_addPublicationBtnActionPerformed
    public static String showAuthors(List<Author> authors){
        String names="";
        for(Author auth:authors){
            names+=auth.getFullName()+", ";
        }
        return names;
    }
    //For Show or hide all Controls
    private void showAllControls(boolean status) {
        jLabel3.setVisible(status);
        jLabel4.setVisible(status);
        jLabel5.setVisible(status);
        jLabel6.setVisible(status);
        jLabel7.setVisible(status);
        jLabel8.setVisible(status);
        jLabel9.setVisible(status);
        jLabel10.setVisible(status);
        jLabel11.setVisible(status);
        jLabel12.setVisible(status);
        jLabel13.setVisible(status);
        jLabel14.setVisible(status);
        jLabel15.setVisible(status);

        issueNoTF.setVisible(status);
        isbnTF.setVisible(status);
        firstNameTF.setVisible(status);
        lastNameTF.setVisible(status);
        phoneTF.setVisible(status);
        credentialsTF.setVisible(status);
        shortBioTF.setVisible(status);
        streetTF.setVisible(status);
        cityTF.setVisible(status);
        stateTF.setVisible(status);
        zipTF.setVisible(status);

        addAuthorAddressBtn.setVisible(status);
        jPanel1.setVisible(status);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthorAddressBtn;
    private javax.swing.JButton addPublicationBtn;
    private javax.swing.JTable authorAddressTable;
    private javax.swing.JTable bookListTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityTF;
    private javax.swing.JTextField credentialsTF;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JTextField isbnTF;
    private javax.swing.JTextField issueNoTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JTable magazineListTable;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JTextField shortBioTF;
    private javax.swing.JTextField stateTF;
    private javax.swing.JTextField streetTF;
    private javax.swing.JTextField titleTF;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField zipTF;
    // End of variables declaration//GEN-END:variables

}
